version: "3.8"

services:
  app1:
    image: markruler/nodejs-hello-world
    container_name: app1
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      # - NODE_ENV=production
  app2:
    image: markruler/nodejs-hello-world
    container_name: app2
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
  app3:
    image: markruler/nodejs-hello-world
    container_name: app3
    ports:
      - "5003:5003"
    environment:
      - PORT=5003

  slb:
    image: httpd:2.4.54-alpine
    container_name: slb
    ports:
      - "8080:80"
    volumes:
      - './httpd.conf:/usr/local/apache2/conf/httpd.conf'
      - './ssl_passwd.sh:/usr/local/apache2/ssl_passwd.sh'
      # - './vhosts.conf:/usr/local/apache2/conf/vhosts.conf'
      - '/etc/letsencrypt/live/domain1.example.com/cert.pem:/etc/ssl/certs/domain1/cert.pem'
      - '/etc/letsencrypt/live/domain1.example.com/privkey.pem:/etc/ssl/certs/domain1/privkey.pem'
      - '/etc/letsencrypt/live/domain1.example.com/chain.pem:/etc/ssl/certs/domain1/chain.pem'
      - '/etc/letsencrypt/live/domain2.example.com/cert.pem:/etc/ssl/certs/domain2/cert.pem'
      - '/etc/letsencrypt/live/domain2.example.com/privkey.pem:/etc/ssl/certs/domain2/privkey.pem'
      - '/etc/letsencrypt/live/domain2.example.com/chain.pem:/etc/ssl/certs/domain2/chain.pem'
    depends_on:
      - app1
      - app2
      - app3
