version: "3.8"

services:
  app1:
    image: markruler/nodejs-hello-world
    container_name: app1
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      # - NODE_ENV=production
  app2:
    image: markruler/nodejs-hello-world
    container_name: app2
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
  app3:
    image: markruler/nodejs-hello-world
    container_name: app3
    ports:
      - "5003:5003"
    environment:
      - PORT=5003

  slb:
    image: envoyproxy/envoy:v1.23.0
    container_name: slb
    ports:
      - "9901:9901"
      - "8080:10000"
    volumes:
      - './envoy.yaml:/etc/envoy/envoy.yaml'
    depends_on:
      - app1
      - app2
      - app3
