version: "3.8"

services:
  app1:
    image: markruler/nodejs-hello-world
    container_name: app1
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      # - NODE_ENV=production
  app2:
    image: markruler/nodejs-hello-world
    container_name: app2
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
  app3:
    image: markruler/nodejs-hello-world
    container_name: app3
    ports:
      - "5003:5003"
    environment:
      - PORT=5003

  slb:
    image: haproxy:2.6.1-alpine
    container_name: slb
    ports:
      - "80:80"
      - "8404:8404"
    user: root
    volumes:
      - './haproxy.local.cfg:/usr/local/etc/haproxy/haproxy.cfg'
    depends_on:
      - app1
      - app2
      - app3

networks:
  default:
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24 # 172.16.200.1~172.16.200.255
          gateway: 172.16.200.1
